# Generated by Django 5.2 on 2025-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('rider', 'Rider'), ('staff', 'Staff')], default='staff', max_length=16),
        ),
    ]
