# Generated by Django 5.2 on 2025-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rides_dropoff_location_rides_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='pickup_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
