# Generated by Django 5.2 on 2025-04-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_rides_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('dropoff', 'Dropoff'), ('enroute', 'En Route'), ('pending', 'Pending'), ('pickup', 'Pickup')], default='pending', max_length=16),
        ),
    ]
